name: CI Pipeline
on: [push]
jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Test
        run: npm run test-ci

      - name: Generating coverage badges
        uses: jpb06/jest-badges-action@latest
        with:
          branches: main
