name: CI Pipeline

on:
  push:
    branches:
      - '**'

jobs:
  testing:
    name: Generate test coverage badges
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install modules
        run: npm install

      - name: Run CI checks
        run: npm run ci

      - name: Generating coverage badges
        uses: jpb06/coverage-badges-action@latest
        with:
          branches: main
          badges-icon: vitest
          output-folder: ./badges/jest
