name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  testing:
    name: Generate test coverage badges
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install modules
        run: npm install

      - name: Check linting
        run: npm run lint

      - name: Run tests
        run: npm run test:withCoverage

      - name: Type checks including generated code
        run: npm run tsc

      - name: Generating coverage badges
        uses: jpb06/coverage-badges-action@latest
        with:
          branches: main
          badges-icon: vitest
          output-folder: ./badges/jest
